### ISSUE TITLE
The processor find_replace is documented but nowhere to be found.

### ISSUE THREAD

**Issue by jbothma** [frictionlessdata/datapackage-pipelines#119]
In order to submit an issue, please ensure you can check the following. Thanks!

* [ ] Declare which version of Python you are using (`python --version`)
* [ ] Declare which operating system you are using

**Comment by akariv** [comment]
This is the processor:
https://github.com/frictionlessdata/datapackage-pipelines/blob/master/datapackage_pipelines/lib/find_replace.py

**Comment by jbothma** [comment]
Bah! I was searching in `git log -p master` instead of `git log -p origin/master`. Apologies.
