### ISSUE TITLE
Human-readable datapackage.json

### ISSUE THREAD

**Issue by AcckiyGerman** [frictionlessdata/datapackage-pipelines#120]
**As a user who read the final datapackage,
As a developer, who debug programs, based on DPP,
I want to have fancy printed descriptor, so I could easy read it.**
(Original https://github.com/datahq/datahub-qa/issues/87)

Now any processed descriptor looks not friendly:
![image](https://user-images.githubusercontent.com/11707682/35920293-2f72e382-0c20-11e8-81f4-1543b5f69e3e.png)

## Analysis
It is very easy to fix how json look here:
https://github.com/frictionlessdata/datapackage-pipelines/blob/ccf920c5b574b050776df6dcc433e5a2d853f27b/datapackage_pipelines/lib/dump/dumper_base.py#L200
We could add `indent=2,` and get much more readable output:
![image](https://user-images.githubusercontent.com/11707682/35920438-8b82ac20-0c20-11e8-9fa0-384efda8b3f2.png)

## consequences

- need to fix 3 tests in the DPP
- need to fix a lot of tests in dependent libs & programs
- descriptor file size could increase up to 30% (this will not impact the performance, coz usual descriptor size is few kilobytes)

@akariv what do you think?

**Comment by pwalsh** [comment]
wouldn't this break the data transfer protocol in DPP?

**Comment by akariv** [comment]
This is just for the descriptors that are dumped to S3 / filesystem.
We can add a new parameter `pretty-descriptor: true` which controls it and
by default is false.

Dima please go ahead and send a PR for this.

**Comment by AcckiyGerman** [comment]
The PR with the 'pretty-descriptor' ability: https://github.com/frictionlessdata/datapackage-pipelines/pull/121

**Comment by AcckiyGerman** [comment]
FIXED:
https://github.com/frictionlessdata/datapackage-pipelines/commit/ce3cae4d59ff128a488842adef71195854e0052c
Tests fixed:
https://github.com/frictionlessdata/datapackage-pipelines/pull/122
