### ISSUE TITLE
SyntaxError in specs.py

### ISSUE THREAD

**Issue by loleg** [frictionlessdata/datapackage-pipelines#141]
In a fresh install of dpp on Python 3.5 from PyPi (1.7.1) or GitHub, I get this error:

```
    specs: Iterator[PipelineSpec] = find_specs(root_dir)
         ^
SyntaxError: invalid syntax
```

https://github.com/frictionlessdata/datapackage-pipelines/blob/53d29c20c5968d11e9c5bb7bb53f185b66cf8af7/datapackage_pipelines/specs/specs.py#L59

It looks to me like [Type Hinting](https://www.python.org/dev/peps/pep-0484/) using the [typing helper](https://docs.python.org/3/library/typing.html) is not compatible with my version of Python. It would be good to state the minimum requirement in the README.

**Comment by akariv** [comment]
Hey, if you're up to it, could you send a PR with better wording for the
README?

Thanks!
