### ISSUE TITLE
Support for data validation and validation reports

### ISSUE THREAD

**Issue by cyberbikepunk** [frictionlessdata/datapackage-pipelines#2]
I need this feature for the [ESIF pipeline](https://github.com/os-data/eu-structural-funds). I thought it might be a good idea to implement it directly in the framework.

[ ] - Add optional *data* validation and reporting support to the function [`ingest`](https://github.com/frictionlessdata/datapackage-pipelines/blob/master/datapackage_pipelines/wrapper/wrapper.py)
[ ] - Add a toggle for data validation and reporting on pipeline processors.

@akariv Can you give me feedback on this please?

**Comment by akariv** [comment]
Can you please elaborate on the types of reporting and validations you have in mind?

**Comment by cyberbikepunk** [comment]
## Data validation

Right now you validate the schemas only (in `ingest`):

```
 schema.validate(dp)
```

I would like to validate each resource contents against its schema.

## Report

Produce a file listing the errors during both schema and data validation.

## Code snippet

@roll suggested I used the `Table` class whilst waiting for the `goodtables` refactoring.

```
from jsontableschema import Table

# Data from WEB, schema from MEMORY
SOURCE = 'https://raw.githubusercontent.com/okfn/jsontableschema-py/master/data/data_infer.csv'
SCHEMA = {'fields': [{'name': 'id', 'type': 'integer'}, {'name': 'age', 'type': 'integer'}, {'name': 'name', 'type': 'string'}] }

# If schema is not passed it will be inferred
table = Table(SOURCE, schema=SCHEMA)
rows = table.iter()
while True:
   try:
       print(next(rows))
   except StopIteration:
       break
   except Exception as exception:
       print(exception)
```

**Comment by pwalsh** [comment]
I think it is great to check the data itself, but probably does not belong to ingest unless optional, because it will increase runtime significantly. Probably better as a processor in the pipeline that can be used at whichever points the author needs.

**Comment by cyberbikepunk** [comment]
Thanks @pwalsh I ended up realizing that and I actually started experimenting my validation processor.

**Comment by akariv** [comment]
@cyberbikepunk I added global validation as per your suggestion.
