### ISSUE TITLE
Samples directory moved

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/datapackage-pipelines#24]
README.md example references spec in current directory when it should reference spec in ./samples/ directory.

In order to submit an issue, please ensure you can check the following. Thanks!

~* [ ] Declare which version of Python you are using (`python --version`)~: Docker
* [ ] Declare which operating system you are using: macOS Sierra

**Comment by akariv** [comment]
Closing as well:

https://github.com/frictionlessdata/datapackage-pipelines/pull/25#issuecomment-280155041
