### ISSUE TITLE
Provide more detailed error message during data validation

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/datapackage-pipelines#31]
> In any case, when using the set_types standard processor, it will validate and transform the input data with the new types

When setting types, if the data does not conform to the `constraints` or `type` set in the schema, it will fail:

```
INFO    :Main    :dump.to_path: jsontableschema.exceptions.ConstraintError: The field 'Aggregate' must not be more than 10
```

```
INFO    :Main    :dump.to_path: jsontableschema.exceptions.InvalidDateType: time data '523' does not match format '%Y-%m-%d'
```

It would be helpful if the processor provided, say, the row/resource that failed the check.  Something equivalent to the Good Tables output.  Or, provide the option not to do a data validation on `set_types` so that I can manually run `goodtables` afterwards.

**Comment by akariv** [comment]
This was fixed some time ago, closing now.
