### ISSUE TITLE
Add local resources via add_resource processor

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/datapackage-pipelines#58]
As part of https://github.com/frictionlessdata/pilot-dm4t/issues/21, I'm using datapackage-pipelines to read some large files I have stored locally.  However, only remote resources are supported by the `add_resource` processor:

    "You can only add remote resources using this processor"

https://github.com/frictionlessdata/datapackage-pipelines/blob/master/datapackage_pipelines/lib/add_resource.py#L11

To work around this, I am serving them via a local HTTP server.  Is there any intention of supporting local resources in the future?

**Comment by akariv** [comment]
This is a wording issue.
It actually means 'external' resources (v.s streamed ones).
You can most definitely specify a local path as the url.

**Comment by akariv** [comment]
Opened #59

**Comment by danfowler** [comment]
Great, thanks!
