### ISSUE TITLE
dump.to_sql should detect sql engine problems before starting to download

### ISSUE THREAD

**Issue by OriHoch** [frictionlessdata/datapackage-pipelines#63]
### reproduction steps
* start scraping some data using dump.to_sql but with invalid SQL engine setting

#### expected
* milliseconds after running should fail with an error regarding failure to connect to SQL server

#### actual
* pipeline starts running
* might download some data, do some stuff
* only when it reaches the dump.to_sql it will fail

### notes
* the more general fix would be to allow processors a `pre` step - before data is streamed
* not sure if such an option exists today or not
* then, dump.to_sql will try to connect to SQL on this `pre` step

**Comment by akariv** [comment]
Anything that's done before the `spew` is essentially the `pre` step.
I will add to `SqlDumper` a connection test.

**Comment by akariv** [comment]
Fixed in c0b3eac9fb17671826cad406c0470e35e12a8301
