### ISSUE TITLE
Tag and create GitHub releases for each version we release

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/datapackage-pipelines#74]
Even though we're already on version `1.0.23`, there are no tags for it (see https://github.com/frictionlessdata/datapackage-pipelines/releases). We should tag the release commits as part of our release process, so it's easier for others to checkout the code on a specific version.

**Comment by akariv** [comment]
Agreed.
How do you propose we do that (other than manually, of course)?

**Comment by vitorbaptista** [comment]
I'm not aware of any tool to help us here, so I'd simply do it manually.

**Comment by akariv** [comment]
Doing that manually atm.
